### ISSUE TITLE
NBT tags for vanilla crafting table

### ISSUE THREAD

**Issue by GedeonGrays** [GTNewHorizons/CraftTweaker#15]
Hello o/

**Modpack:** Not GTNH
**Minecraft:** 1.7.10
**CraftTweaker:** 3.2.13

I want to be able to add NBT tags for vanilla crafting table recipes with CraftTweaker. 
For example, _**Sharpness V Book -> Diamond Sword**_. But currently, if I use the output of _/mt hand_ as an ingredient, any enchanted book will match the added recipe.

Could you please consider this issue and implement if possible?

P.S. If needed, I will be happy to answer clarifying questions to the best of my ability.

**Comment by glowredman** [comment]
That is already possible, see [http://minetweaker3.powerofbytes.com/wiki/Tutorial:Advanced_Recipes](https://web.archive.org/web/20200630234734/http://minetweaker3.powerofbytes.com/wiki/Tutorial:Advanced_Recipes) (via Wayback Machine).

**Comment by GedeonGrays** [comment]
> In short: use `onlyWithTag`, not `withTag`.

From what I understand, we tested this option, but it just didn't work. I'll check this point again with the people who handle the recipes and come back late.

**Comment by GedeonGrays** [comment]
@glowredman
Yeah, we must have missed something. Your option works, thanks for your help.

I apologize for my intrusiveness, but could you please advise if there is any detailed documentation on the recipe functions in vanilla crafting table? Maybe something else besides that: https://docs.blamejared.com/MineTweaker/en/tutorials/1.7.x/advanced_recipes#function-recipes
